# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jjhu/Temp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jjhu/Temp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jjhu/Temp/CMakeFiles /home/jjhu/Temp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jjhu/Temp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named demo

# Build rule for target.
demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 demo
.PHONY : demo

# fast build rule for target.
demo/fast:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/build
.PHONY : demo/fast

#=============================================================================
# Target rules for targets named gen_constraints

# Build rule for target.
gen_constraints: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen_constraints
.PHONY : gen_constraints

# fast build rule for target.
gen_constraints/fast:
	$(MAKE) -f CMakeFiles/gen_constraints.dir/build.make CMakeFiles/gen_constraints.dir/build
.PHONY : gen_constraints/fast

#=============================================================================
# Target rules for targets named gen_cross_index

# Build rule for target.
gen_cross_index: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen_cross_index
.PHONY : gen_cross_index

# fast build rule for target.
gen_cross_index/fast:
	$(MAKE) -f CMakeFiles/gen_cross_index.dir/build.make CMakeFiles/gen_cross_index.dir/build
.PHONY : gen_cross_index/fast

demo.o: demo.cpp.o
.PHONY : demo.o

# target to build an object file
demo.cpp.o:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/demo.cpp.o
.PHONY : demo.cpp.o

demo.i: demo.cpp.i
.PHONY : demo.i

# target to preprocess a source file
demo.cpp.i:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/demo.cpp.i
.PHONY : demo.cpp.i

demo.s: demo.cpp.s
.PHONY : demo.s

# target to generate assembly for a file
demo.cpp.s:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/demo.cpp.s
.PHONY : demo.cpp.s

gen_constraints.o: gen_constraints.cpp.o
.PHONY : gen_constraints.o

# target to build an object file
gen_constraints.cpp.o:
	$(MAKE) -f CMakeFiles/gen_constraints.dir/build.make CMakeFiles/gen_constraints.dir/gen_constraints.cpp.o
.PHONY : gen_constraints.cpp.o

gen_constraints.i: gen_constraints.cpp.i
.PHONY : gen_constraints.i

# target to preprocess a source file
gen_constraints.cpp.i:
	$(MAKE) -f CMakeFiles/gen_constraints.dir/build.make CMakeFiles/gen_constraints.dir/gen_constraints.cpp.i
.PHONY : gen_constraints.cpp.i

gen_constraints.s: gen_constraints.cpp.s
.PHONY : gen_constraints.s

# target to generate assembly for a file
gen_constraints.cpp.s:
	$(MAKE) -f CMakeFiles/gen_constraints.dir/build.make CMakeFiles/gen_constraints.dir/gen_constraints.cpp.s
.PHONY : gen_constraints.cpp.s

gen_cross_index.o: gen_cross_index.cpp.o
.PHONY : gen_cross_index.o

# target to build an object file
gen_cross_index.cpp.o:
	$(MAKE) -f CMakeFiles/gen_cross_index.dir/build.make CMakeFiles/gen_cross_index.dir/gen_cross_index.cpp.o
.PHONY : gen_cross_index.cpp.o

gen_cross_index.i: gen_cross_index.cpp.i
.PHONY : gen_cross_index.i

# target to preprocess a source file
gen_cross_index.cpp.i:
	$(MAKE) -f CMakeFiles/gen_cross_index.dir/build.make CMakeFiles/gen_cross_index.dir/gen_cross_index.cpp.i
.PHONY : gen_cross_index.cpp.i

gen_cross_index.s: gen_cross_index.cpp.s
.PHONY : gen_cross_index.s

# target to generate assembly for a file
gen_cross_index.cpp.s:
	$(MAKE) -f CMakeFiles/gen_cross_index.dir/build.make CMakeFiles/gen_cross_index.dir/gen_cross_index.cpp.s
.PHONY : gen_cross_index.cpp.s

itml.o: itml.cpp.o
.PHONY : itml.o

# target to build an object file
itml.cpp.o:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/itml.cpp.o
	$(MAKE) -f CMakeFiles/gen_constraints.dir/build.make CMakeFiles/gen_constraints.dir/itml.cpp.o
	$(MAKE) -f CMakeFiles/gen_cross_index.dir/build.make CMakeFiles/gen_cross_index.dir/itml.cpp.o
.PHONY : itml.cpp.o

itml.i: itml.cpp.i
.PHONY : itml.i

# target to preprocess a source file
itml.cpp.i:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/itml.cpp.i
	$(MAKE) -f CMakeFiles/gen_constraints.dir/build.make CMakeFiles/gen_constraints.dir/itml.cpp.i
	$(MAKE) -f CMakeFiles/gen_cross_index.dir/build.make CMakeFiles/gen_cross_index.dir/itml.cpp.i
.PHONY : itml.cpp.i

itml.s: itml.cpp.s
.PHONY : itml.s

# target to generate assembly for a file
itml.cpp.s:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/itml.cpp.s
	$(MAKE) -f CMakeFiles/gen_constraints.dir/build.make CMakeFiles/gen_constraints.dir/itml.cpp.s
	$(MAKE) -f CMakeFiles/gen_cross_index.dir/build.make CMakeFiles/gen_cross_index.dir/itml.cpp.s
.PHONY : itml.cpp.s

utility.o: utility.cpp.o
.PHONY : utility.o

# target to build an object file
utility.cpp.o:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/utility.cpp.o
	$(MAKE) -f CMakeFiles/gen_constraints.dir/build.make CMakeFiles/gen_constraints.dir/utility.cpp.o
	$(MAKE) -f CMakeFiles/gen_cross_index.dir/build.make CMakeFiles/gen_cross_index.dir/utility.cpp.o
.PHONY : utility.cpp.o

utility.i: utility.cpp.i
.PHONY : utility.i

# target to preprocess a source file
utility.cpp.i:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/utility.cpp.i
	$(MAKE) -f CMakeFiles/gen_constraints.dir/build.make CMakeFiles/gen_constraints.dir/utility.cpp.i
	$(MAKE) -f CMakeFiles/gen_cross_index.dir/build.make CMakeFiles/gen_cross_index.dir/utility.cpp.i
.PHONY : utility.cpp.i

utility.s: utility.cpp.s
.PHONY : utility.s

# target to generate assembly for a file
utility.cpp.s:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/utility.cpp.s
	$(MAKE) -f CMakeFiles/gen_constraints.dir/build.make CMakeFiles/gen_constraints.dir/utility.cpp.s
	$(MAKE) -f CMakeFiles/gen_cross_index.dir/build.make CMakeFiles/gen_cross_index.dir/utility.cpp.s
.PHONY : utility.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... demo"
	@echo "... edit_cache"
	@echo "... gen_constraints"
	@echo "... gen_cross_index"
	@echo "... rebuild_cache"
	@echo "... demo.o"
	@echo "... demo.i"
	@echo "... demo.s"
	@echo "... gen_constraints.o"
	@echo "... gen_constraints.i"
	@echo "... gen_constraints.s"
	@echo "... gen_cross_index.o"
	@echo "... gen_cross_index.i"
	@echo "... gen_cross_index.s"
	@echo "... itml.o"
	@echo "... itml.i"
	@echo "... itml.s"
	@echo "... utility.o"
	@echo "... utility.i"
	@echo "... utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

